"""remove UserImage

Revision ID: a471a185dd5f
Revises: f9e6045f54ed
Create Date: 2025-12-18 16:28:18.370618

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'a471a185dd5f'
down_revision = 'f9e6045f54ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_image_tags')
    op.drop_table('user_images')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('result',
               existing_type=sqlite.JSON(),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('result',
               existing_type=sa.Text(),
               type_=sqlite.JSON(),
               existing_nullable=True)

    op.create_table('user_images',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=True),
    sa.Column('image_path', sa.VARCHAR(), nullable=True),
    sa.Column('is_detected', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_image_tags',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_image_id', sa.VARCHAR(), nullable=True),
    sa.Column('tag_name', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_image_id'], ['user_images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
